start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

accordion-padding = 10
on-focus-changed = ['move-mouse window-lazy-center']

[[on-window-detected]]
if.app-id = 'com.brave.Browser' #Brave
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92' #Cursor
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.facebook.archon.developerID' #Messenger
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap' #Slack
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp' #WhatsApp
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chat'
run = 'move-node-to-workspace 7'


[[on-window-detected]]
if.app-id = 'com.openai.chat' #ChatGPT
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-name-regex-substring = 'Gemini'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'md.obsidian' #Obsidian
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'dev.kdrag0n.MacVirt' #OrbStack
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.google.Chrome' #Chrome
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'iTerm2'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'design.yugen.Flow'
run = ['layout floating']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
10 = 'secondary'

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]

# Change window focus within space
cmd-h = 'focus left --boundaries-action stop'
# cmd-j = 'focus down'
# cmd-k = 'focus up' // I use this for Slack
cmd-l = 'focus right --boundaries-action stop'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

# TODO: Check if this is working
ctrl-alt-h = ['resize width -10', 'resize width -10']
ctrl-alt-j = ['resize height +10', 'resize height +10']
ctrl-alt-k = ['resize height -10', 'resize height -10']
ctrl-alt-l = ['resize width +10', 'resize width +10']


ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'

ctrl-cmd-1 = 'workspace 6'
ctrl-cmd-2 = 'workspace 7'
ctrl-cmd-3 = 'workspace 8'
ctrl-cmd-4 = 'workspace 9'
ctrl-cmd-5 = 'workspace 10'

ctrl-cmd-t = 'layout floating tiling'

ctrl-s = 'focus-monitor left'
ctrl-g = 'focus-monitor right'

ctrl-shift-s = 'move-node-to-monitor left'
ctrl-shift-g = 'move-node-to-monitor right'

ctrl-cmd-shift-s = 'move-workspace-to-monitor prev'
ctrl-cmd-shift-g = 'move-workspace-to-monitor next'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'


ctrl-cmd-shift-1 = 'move-node-to-workspace 6'
ctrl-cmd-shift-2 = 'move-node-to-workspace 7'
ctrl-cmd-shift-3 = 'move-node-to-workspace 8'
# Can't use 4 here as I use it for screenshot shortcut
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-cmd-shift-5 = 'move-node-to-workspace 10'

ctrl-alt-r = 'reload-config'

ctrl-cmd-s = 'layout tiles h_accordion'
